### ISSUE TITLE
Fusion 7.0.x on Yosemite mac fails

### ISSUE THREAD

**Issue by symgryph** [jedi4ever/veewee#1023]
```text
/Users/tjmunn/Veewee/veewee/lib/fission/config.rb:41:in `initialize': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /Users/tjmunn/Veewee/veewee/lib/fission.rb:36:in `new'
	from /Users/tjmunn/Veewee/veewee/lib/fission.rb:36:in `config'
	from /Users/tjmunn/Veewee/veewee/lib/veewee/provider/vmfusion/provider.rb:14:in `check_requirements'
	from /Users/tjmunn/Veewee/veewee/lib/veewee/provider/core/provider.rb:28:in `initialize'
	from /Users/tjmunn/Veewee/veewee/lib/veewee/providers.rb:16:in `new'
	from /Users/tjmunn/Veewee/veewee/lib/veewee/providers.rb:16:in `[]'
	from /Users/tjmunn/Veewee/veewee/lib/veewee/environment.rb:225:in `get_box'
	from /Users/tjmunn/Veewee/veewee/lib/veewee/command/fusion.rb:23:in `build'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/tjmunn/Veewee/veewee/bin/veewee:24:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/bin/veewee:23:in `load'
	from /usr/local/lib/ruby/gems/2.1.0/bin/veewee:23:in `<main>'
```

**Comment by kral2** [comment]
Hi, same symptoms here. Had you any chance to look at the issue?

**Comment by symgryph** [comment]
I never got it to work. Seems like 7.0 or 7.1 don't process correctly. I did do some sym linking but never got it to work.

**Comment by symgryph** [comment]
Still doesn't work. No idea why.

**Comment by symgryph** [comment]
Just noticed that I am getting the 'fission' error with the currentest. Should I try an earlier version like stable?

**Comment by symgryph** [comment]
I do admit that packer seems to work fine with fusion. I guess I will just use that.

**Comment by n0ts** [comment]
I think that this is problem about fission gem.

**Comment by symgryph** [comment]
I have no idea how to fix. Is it a sep (somebody else's problem) field situation?

**Comment by n0ts** [comment]
Hi, I fix a this problem.
My PR is https://github.com/jedi4ever/veewee/pull/1054.

Please try it, Thanks.

**Comment by n0ts** [comment]
@symgryph Hi, I fix a this problem.
My PR is #1054.

Please try it, Thanks.

**Comment by mpapis** [comment]
fixed with #1054 - please let me know if not

**Comment by symgryph** [comment]
Just installed. Works great!

**Comment by symgryph** [comment]
It worked! Thanks!
