### ISSUE TITLE
Can't connect to web server?

### ISSUE THREAD

**Issue by NathanCisco** [jedi4ever/veewee#1065]
Stopping webserver
/Users/.../git/veewee/lib/veewee/provider/core/helper/web.rb:16:in `wait_for_http_request': File "/Users/.../git/veewee/definitions/devnet-dev-base/preseed.cfg" was not requested as "/preseed.cfg" in 300 seconds, are you using firewall blocking connections to port: 7122? (RuntimeError)

Hi

I see the error above when running:

veewee vbox build 'devnet-dev-base' --force

Where:

veewee vbox define 'devnet-dev-base' 'ubuntu-14.04-server-amd64'

And where:

 :iso_file => "ubuntu-14.04.2-desktop-amd64.iso",
 :iso_src => "http://releases.ubuntu.com/14.04/ubuntu-14.04.2-desktop-amd64.iso",

$ pwd
/Users/.../git/veewee
$ ls iso
VBoxGuestAdditions_4.3.26.iso		ubuntu-14.04.2-desktop-amd64.iso

When running the command, and waiting for the 300 sec timeout, I get (using the IP address shown in the full log below):

$ ping 10.0.2.2
PING 10.0.2.2 (10.0.2.2): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
^C
--- 10.0.2.2 ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss

Any ideas please?

Many thanks

Nathan

Full log:

veewee vbox build 'devnet-dev-base' --force
Downloading vbox guest additions iso v 4.3.26 - http://download.virtualbox.org/virtualbox/4.3.26/VBoxGuestAdditions_4.3.26.iso
Checking if isofile VBoxGuestAdditions_4.3.26.iso already exists.
Full path: /Users/.../git/veewee/iso/VBoxGuestAdditions_4.3.26.iso

The isofile VBoxGuestAdditions_4.3.26.iso already exists.
Building Box devnet-dev-base with Definition devnet-dev-base:
- debug : false
- cwd : /Users/.../git/veewee
- force : true
- nogui : false
- auto : false
- checksum : false
- redirectconsole : false
- postinstall_include : []
- postinstall_exclude : []
- skip_to_postinstall : false

The isofile ubuntu-14.04.2-desktop-amd64.iso already exists.
VBoxManage unregistervm  "devnet-dev-base" --delete
Deleting vm devnet-dev-base
Creating vm devnet-dev-base : 2048M - 1 CPU - Ubuntu_64
Creating new harddrive of size 30720, format VDI, variant Standard 
Attaching disk: /Users/.../VirtualBox VMs/devnet-dev-base/devnet-dev-base1.vdi
Mounting cdrom: /Users/.../git/veewee/iso/ubuntu-14.04.2-desktop-amd64.iso
Mounting guest additions: /Users/.../git/veewee/iso/VBoxGuestAdditions_4.3.26.iso
Finding unused TCP port in range: 7222 - 7262
Selected TCP port 7222
Finding unused TCP port in range: 7222 - 7262
Selected TCP port 7222
Waiting 4 seconds for the machine to boot
Finding unused TCP port in range: 7122 - 7199
Selected TCP port 7122

Typing:[1]: <Esc><Esc><Enter>
Starting a webserver 10.0.2.2:7122, check your firewall if nothing happens
Typing:[2]: /install/vmlinuz noapic preseed/url=http://10.0.2.2:7122/preseed.cfg 
Typing:[3]: debian-installer=en_US auto locale=en_US kbd-chooser/method=us 
Typing:[4]: hostname=devnet-dev-base 
Typing:[5]: fb=false debconf/frontend=noninteractive 
Typing:[6]: keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=us keyboard-configuration/variant=us console-setup/ask_detect=false 
Typing:[7]: initrd=/install/initrd.gz -- <Enter>
Done typing.

Stopping webserver
/Users/.../git/veewee/lib/veewee/provider/core/helper/web.rb:16:in `wait_for_http_request': File "/Users/.../git/veewee/definitions/devnet-dev-base/preseed.cfg" was not requested as "/preseed.cfg" in 300 seconds, are you using firewall blocking connections to port: 7122? (RuntimeError)
	from /Users/.../git/veewee/lib/veewee/provider/core/box/build.rb:242:in `block in handle_kickstart'
	from /Users/.../git/veewee/lib/veewee/provider/core/box/build.rb:241:in `each'
	from /Users/.../git/veewee/lib/veewee/provider/core/box/build.rb:241:in `each_with_index'
	from /Users/.../git/veewee/lib/veewee/provider/core/box/build.rb:241:in `handle_kickstart'
	from /Users/.../git/veewee/lib/veewee/provider/core/box/build.rb:82:in `kickstart'
	from /Users/.../git/veewee/lib/veewee/provider/core/box/build.rb:113:in `build'
	from /Users/.../git/veewee/lib/veewee/provider/virtualbox/box/build.rb:10:in `build'
	from /Users/.../git/veewee/lib/veewee/command/vbox.rb:22:in `build'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/.../git/veewee/bin/veewee:24:in `<top (required)>'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/bin/veewee:23:in `load'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/bin/veewee:23:in `<main>'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/bin/ruby_executable_hooks:15:in `eval'
	from /Users/.../.rvm/gems/ruby-2.2.1@veewee/bin/ruby_executable_hooks:15:in `<main>'

**Comment by NathanCisco** [comment]
I also tried with Fusion, but got the same error, and I also tested whether the port was open during the 300 second window. The first test below is Fusion (veewee fusion build 'devnet-dev-base' --force)

Port Scan has started…

Port Scanning host: 192.168.91.1

	 Open TCP Port: 	7122
Port Scan has completed…

Then I tested again with VBox (veewee vbox build 'devnet-dev-base' --force). In this case I got:

Port Scan has started…

Port Scanning host: 10.0.2.2

Port Scan has completed…

Which is to say that the port 7122 was not open on VBox.
