### ISSUE TITLE
Gem error on Mac OS X

### ISSUE THREAD

**Issue by rightisleft** [jedi4ever/veewee#1092]
Howdy,
I follow the most recent documentation to configure veewee:

When trying to build my first vbox, i get the following:

```
➜  veewee git:(master) veewee vbox build appliance
/Users/zero/projects/appliance/veewee/lib/veewee/provider/core/helper/ssh.rb:3:in `require': cannot load such file -- net/scp (LoadError)
	from /Users/zero/projects/appliance/veewee/lib/veewee/provider/core/helper/ssh.rb:3:in `<top (required)>'
	from /Users/zero/projects/appliance/veewee/lib/veewee/provider/core/box.rb:2:in `require'
	from /Users/zero/projects/appliance/veewee/lib/veewee/provider/core/box.rb:2:in `<top (required)>'
	from /Users/zero/projects/appliance/veewee/lib/veewee/provider/virtualbox/box.rb:1:in `require'
	from /Users/zero/projects/appliance/veewee/lib/veewee/provider/virtualbox/box.rb:1:in `<top (required)>'
	from /Users/zero/projects/appliance/veewee/lib/veewee/provider/virtualbox/provider.rb:2:in `require'
	from /Users/zero/projects/appliance/veewee/lib/veewee/provider/virtualbox/provider.rb:2:in `<top (required)>'
	from /Users/zero/projects/appliance/veewee/lib/veewee/providers.rb:14:in `require'
	from /Users/zero/projects/appliance/veewee/lib/veewee/providers.rb:14:in `[]'
	from /Users/zero/projects/appliance/veewee/lib/veewee/environment.rb:225:in `get_box'
	from /Users/zero/projects/appliance/veewee/lib/veewee/command/vbox.rb:22:in `build'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/zero/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/zero/projects/appliance/veewee/bin/veewee:24:in `<top (required)>'
	from /Users/zero/.rvm/gems/ruby-2.2.1/bin/veewee:23:in `load'
	from /Users/zero/.rvm/gems/ruby-2.2.1/bin/veewee:23:in `<main>'
	from /Users/zero/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/zero/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

```
➜  veewee git:(master) gem list

*** LOCAL GEMS ***

ansi (1.3.0)
bigdecimal (1.2.6)
builder (3.2.2)
bundler (1.11.2)
bundler-unload (1.0.2)
CFPropertyList (2.3.2)
childprocess (0.5.9)
diff-lcs (1.2.5)
em-winrm (0.7.0)
eventmachine (1.0.9.1)
excon (0.47.0)
executable-hooks (1.3.2)
ffi (1.9.10)
fission (0.5.0)
fog (1.37.0)
fog-aliyun (0.1.0)
fog-atmos (0.1.0)
fog-aws (0.8.1)
fog-brightbox (0.10.1)
fog-core (1.36.0)
fog-dynect (0.0.2)
fog-ecloud (0.3.0)
fog-google (0.1.0)
fog-json (1.0.2)
fog-local (0.2.1)
fog-powerdns (0.1.1)
fog-profitbricks (0.0.5)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-serverlove (0.1.2)
fog-softlayer (1.1.0)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (0.6.0)
fog-xenserver (0.2.3)
fog-xml (0.1.2)
formatador (0.2.5)
gem-content (1.0.0)
gem-wrappers (1.2.7)
grit (2.5.0)
gssapi (1.2.0)
gyoku (1.3.1)
highline (1.7.8)
httpclient (2.7.1)
i18n (0.7.0)
inflecto (0.0.2)
io-console (0.4.3)
ipaddress (0.8.3)
json (1.8.3, 1.8.1)
little-plugger (1.1.4)
log4r (1.1.10)
logging (2.0.0)
mime-types (1.25.1)
mini_portile2 (2.0.0)
mixlib-log (1.6.0)
multi_json (1.11.2)
net-ssh (3.0.2)
nokogiri (1.6.7.2)
nori (2.6.0)
open4 (1.3.4)
os (0.9.6)
Platform (0.4.0)
popen4 (0.1.2)
posix-spawn (0.3.11)
progressbar (0.21.0)
psych (2.0.8)
rake (10.5.0, 10.4.2)
rbvmomi (1.8.2)
rdoc (4.2.0)
rspec (2.99.0)
rspec-core (2.99.2)
rspec-expectations (2.99.2)
rspec-mocks (2.99.4)
ruby-vnc (1.0.1)
rubygems-bundler (1.4.4)
rubyntlm (0.4.0)
rvm (1.11.3.9)
thor (0.19.1)
to_slug (1.0.8)
trollop (2.1.2)
uuidtools (2.1.5)
winrm (1.3.6)
xml-simple (1.1.5)
```

**Comment by npersad** [comment]
add the net-scp dependency to the veewee.gemspec file

s.add_dependency "net-scp", ">=1.2.1"
